modLoader="javafml"
loaderVersion="[47,)" # Для Forge 47.2.0 (1.20.1)
license="MIT"

[[mods]]
modId="testmod"
version="1.0.0"
displayName="Test Mod"
authors="Defender13"
description='''
Мой первый мод для Minecraft!
Добавляет рубины в игру.
'''

# Зависимости (можно оставить как есть)
[[dependencies.testmod]]
modId="forge"
mandatory=true
versionRange="[47.2.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.testmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"